name: "01-02 Build Hotfix Image"
run-name: "hotfix-${{ github.run_number }}"

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

concurrency:
  group: build-${{ github.ref }}

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      version_tag: ${{ github.ref_name }}
      run_name: "hotfix-${{ github.run_number }}"
    secrets: inherit
  
  save_version:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Save version tag to artifact
        run: echo "${{ needs.build.outputs.unique_version_tag }}" > version_tag.txt
      
      - name: Upload version tag artifact
        uses: actions/upload-artifact@v4
        with:
          name: version-tag
          path: version_tag.txt
          retention-days: 1