name: "01-02 Build Hotfix Image"
run-name: "hotfix-${{ github.run_number }}"

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

concurrency:
  group: build-${{ github.ref }}

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      version_tag: ${{ github.ref_name }}
      run_name: "hotfix-${{ github.run_number }}"
    secrets: inherit
  
  trigger_deployment:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Trigger deployment workflow
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: '03-02-deploy-hotfix-to-test.yml',
              ref: '${{ github.ref }}',
              inputs: {
                version_tag: '${{ needs.build.outputs.unique_version_tag }}',
              }
            })