name: "01-02 Build Hotfix Image"
run-name: "hotfix-${{ github.run_number }}"

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

concurrency:
  group: build-${{ github.ref }}

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      version_tag: ${{ github.ref_name }}
      run_name: "hotfix-${{ github.run_number }}"
    secrets: inherit