name: "01-02 Build Hotfix Image"
run-name: "hotfix-${{ github.run_number }}"

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch name to use as version tag'
        required: true
        type: string

permissions:
  contents: write
  packages: write

concurrency:
  group: build-${{ github.ref }}

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      version_tag: ${{ github.event.inputs.branch_name }}
      run_name: "hotfix-${{ github.run_number }}"
    secrets: inherit