name: "01-01 Build Image"
run-name: "build-${{ github.run_number }}"

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write
  packages: write

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      version_tag: "build-${{ github.run_number }}"
      run_name: "build-${{ github.run_number }}"
    secrets: inherit