name: "02-01 Deploy to Demo"
run-name: "deploy ${{ inputs.version_tag }} to demo"

on:
  workflow_dispatch:
    inputs:
      version_tag:
        description: 'Version tag'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: 'demo'

    steps:
      - name: Show the version tag
        run: echo ${{ inputs.version_tag  }}

      - name: Deploy application
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://r-systems-cloud.com/api/hooks/git-tests-demo'
          method: 'POST'
          customHeaders: '{"x-api-key": "${{ secrets.DEPLOY_DEMO_APP_KEY }}"}'
          data: '{"image_tag": "${{ inputs.version_tag }}"}'
          timeout: 300000