name: "03-02 Deploy Hotfix to Test"
run-name: "deploy hotfix-${{ github.event.workflow_run.run_number }} to test"

on:
  workflow_dispatch:
    inputs:
      version_tag:
        description: 'Version to deploy'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: 'test'

    steps:
      - name: Show the version tag
        run: echo ${{ inputs.version_tag }}

      - name: Deploy application
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://r-systems-cloud.com/api/hooks/git-tests-test'
          method: 'POST'
          customHeaders: '{"x-api-key": "${{ secrets.DEPLOY_TEST_APP_KEY }}"}'
          data: '{"image_tag": "${{ inputs.version_tag }}"}'
          timeout: 300000