name: "03-02 Deploy Hotfix to Test"
run-name: "deploy hotfix-${{ github.event.workflow_run.run_number }} to test"

on:
  workflow_run:
    workflows: [ "01-02 Build Hotfix Image" ]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    environment:
      name: 'test'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get version tag from build workflow
        id: get_version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          WORKFLOW_RUN_ID="${{ github.event.workflow_run.id }}"
          
          # Get the version_tag input from the triggering workflow
          VERSION_TAG=$(gh api repos/${{ github.repository }}/actions/runs/$WORKFLOW_RUN_ID | jq -r '.inputs.version_tag // empty')
          
          if [ -z "$VERSION_TAG" ]; then
            echo "Error: Could not retrieve version_tag from workflow inputs"
            exit 1
          fi
          
          echo "version_tag=$VERSION_TAG" >> $GITHUB_OUTPUT
          echo "Retrieved version tag: $VERSION_TAG"

      - name: Show the version tag
        run: echo ${{ env.VERSION_TAG }}

      - name: Deploy application
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://r-systems-cloud.com/api/hooks/git-tests-test'
          method: 'POST'
          customHeaders: '{"x-api-key": "${{ secrets.DEPLOY_TEST_APP_KEY }}"}'
          data: '{"image_tag": "${{ steps.get_version.outputs.version_tag }}"}'
          timeout: 300000