name: "Reusable Build Workflow"

on:
  workflow_call:
    inputs:
      version_tag:
        description: 'Version tag for the build'
        required: true
        type: string
      run_name:
        description: 'Run name for the workflow'
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  APP_IMAGE_NAME: lrydzkowski/git-tests

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: ${{ inputs.run_name }}

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set version tag
        run: echo "VERSION_TAG=${{ inputs.version_tag }}" >> $GITHUB_ENV

      - name: Show the version tag
        run: echo ${{ env.VERSION_TAG }}

      - name: Setup .NET Core SDK 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Install API dependencies
        run: dotnet restore

      - name: Build API
        run: dotnet build --configuration Release --no-restore

      - name: Sign in to the container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build APP docker image
        id: docker_api_build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./GitTests/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.APP_IMAGE_NAME }}:latest,${{ env.REGISTRY }}/${{ env.APP_IMAGE_NAME }}:${{ env.VERSION_TAG }}

      - name: Set tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          custom_tag: ${{ env.VERSION_TAG }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ""